CREATE TABLE IF NOT EXISTS BankUser(
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    UserId INT(10) NOT NULL,
    CreatedAt Text NOT NULL,
    ModifiedAt Text
);

CREATE TABLE IF NOT EXISTS Loan(
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    BankUserId INT(10) NOT NULL,
    CreatedAt TEXT NOT NULL,
    ModifiedAt TEXT,
    Amount REAL,
    FOREIGN KEY(BankUserId) REFERENCES BankUser(Id)
);

CREATE TABLE IF NOT EXISTS Account(
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    BankUserId INT(10) NOT NULL,
    AccountNo TEXT UNIQUE NOT NULL,
    IsStudent BOOLEAN CHECK (IsStudent IN (0,1)),
    CreatedAt TEXT NOT NULL,
    Modified TEXT,
    Amount REAL,
    FOREIGN KEY(BankUserId) REFERENCES BankUserId(Id)
);

CREATE TABLE IF NOT EXISTS Deposit(
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    BankUserId INT(10) NOT NULL,
    CreatedAt TEXT NOT NULL,
    Amount REAL NOT NULL,
    FOREIGN KEY(BankUserId) REFERENCES BankUser(Id)
);

