CREATE TABLE IF NOT EXISTS BorgerUser (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL UNIQUE,
    CreatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Address (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BorgerUserId INTEGER NOT NULL,
    Address TEXT NOT NULL,
    CreatedAt TEXT NOT NULL,
    IsValid INTEGER NOT NULL,
    FOREIGN KEY (BorgerUserId) REFERENCES BorgerUser (ID)
);