CREATE TABLE IF NOT EXISTS SkatUser(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL UNIQUE,
    CreatedAt Text NOT NULL,
    IsActive INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS SkatUserYear(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    SkatUserId INTEGER NOT NULL,
    SkatYearId INTEGER NOT NULL,
    UserId INTEGER NOT NULL,
    IsPaid INTEGER NOT NULL,
    Amount INTEGER NOT NULL,
    FOREIGN KEY(SkatUserId) REFERENCES SkatUser(Id),
    FOREIGN KEY(SkatYearId) REFERENCES SkatYear(Id)
);

CREATE TABLE IF NOT EXISTS SkatYear(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Label TEXT NOT NULL,
    CreatedAt TEXT NOT NULL,
    ModifiedAt TEXT,
    StartDate TEXT NOT NULL,
    EndDate TEXT NOT NULL
);



